source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'CYFDataSource_Example', :exclusive => true do
  pod "CYFDataSource", :path => "../"
end

target 'CYFDataSource_Tests', :exclusive => true do
  pod "CYFDataSource", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
